const items = $input.all().map(({ json }) => json);
const carrier = items.find((item) => item?.kind === 'carrier');
const rows = items.filter((item) => item?.id && item.requestKey === carrier?.input?.requestKey);
if (!carrier || !carrier.input || rows.length === 0) throw new Error('preflight requires carrier and full same-key rows');
const canonical = rows.filter((row) => row.reconciliationStatus === 'canonical' && row.canonicalRowID === String(row.id));
if (canonical.length !== 1) throw new Error('preflight reconciliation gate failed');
const row = canonical[0];
if (row.id !== carrier.row.id || row.status !== 'summary_dispatching' || row.leaseOwner !== carrier.row.leaseOwner || row.leaseUntilIso !== carrier.row.leaseUntilIso || Date.parse(row.leaseUntilIso) <= Date.now()) throw new Error('preflight owner gate failed');
const stage = carrier.nextStage;
const done = stage === 'inference' ? row.inferenceResultJson && row.summaryMarkdown : stage === 'upload' ? row.summaryUploadID : stage === 'status' ? row.summaryMessageTS : false;
if (done) return [];
return [{ json: { ...carrier, row, ownerConditions: { id: row.id, requestKey: row.requestKey, status: row.status, reconciliationStatus: 'canonical', canonicalRowID: String(row.id), leaseOwner: row.leaseOwner, leaseUntilIso: row.leaseUntilIso } } }];
