const schema = {
  suspect_stt_candidates_v3: [
    { name: 'candidateKey', type: 'string' }, { name: 'runID', type: 'string' },
    { name: 'streamID', type: 'string' }, { name: 'prevStreamID', type: 'string' },
    { name: 'sourcesJson', type: 'string' }, { name: 'channel', type: 'string' },
    { name: 'threadTS', type: 'string' }, { name: 'summaryRequestKey', type: 'string' },
    { name: 'reconciliationStatus', type: 'string' }, { name: 'canonicalRowID', type: 'string' },
    { name: 'createdAtIso', type: 'string' }, { name: 'updatedAtIso', type: 'string' },
  ],
  stt_jobs_v3: [
    { name: 'attemptKey', type: 'string' }, { name: 'logicalJobKey', type: 'string' },
    { name: 'requestKey', type: 'string' }, { name: 'requestType', type: 'string' },
    { name: 'attempt', type: 'number' }, { name: 'role', type: 'string' },
    { name: 'streamID', type: 'string' }, { name: 'mode', type: 'string' },
    { name: 'durationMinutes', type: 'number' }, { name: 'streamContextJson', type: 'string' },
    { name: 'status', type: 'string' }, { name: 'callbackTokenHash', type: 'string' },
    { name: 'reconciliationStatus', type: 'string' }, { name: 'canonicalRowID', type: 'string' },
    { name: 'dispatchLeaseOwner', type: 'string' }, { name: 'dispatchLeaseUntilIso', type: 'string' },
    { name: 'submittedAtIso', type: 'string' }, { name: 'callbackDeadlineAtIso', type: 'string' },
    { name: 'manualReviewReason', type: 'string' }, { name: 'manualReviewAtIso', type: 'string' },
    { name: 'manualReviewResolution', type: 'string' },
    { name: 'callbackTokenExpiresAtIso', type: 'string' }, { name: 'consumedAtIso', type: 'string' },
    { name: 'channel', type: 'string' }, { name: 'threadTS', type: 'string' },
    { name: 'processingMessageTS', type: 'string' }, { name: 'dialogue', type: 'string' },
    { name: 'language', type: 'string' }, { name: 'errorCode', type: 'string' },
    { name: 'nextRetryAtIso', type: 'string' }, { name: 'retryLeaseOwner', type: 'string' },
    { name: 'retryLeaseUntilIso', type: 'string' }, { name: 'duplicateCount', type: 'number' },
    { name: 'presentationStatus', type: 'string' }, { name: 'presentationLeaseOwner', type: 'string' },
    { name: 'presentationLeaseUntilIso', type: 'string' }, { name: 'presentationAttempt', type: 'number' },
    { name: 'presentationNextRetryAtIso', type: 'string' }, { name: 'presentationErrorCode', type: 'string' },
    { name: 'transcriptUploadID', type: 'string' }, { name: 'analysisUploadID', type: 'string' },
    { name: 'processingMessageUpdatedAtIso', type: 'string' }, { name: 'createdAtIso', type: 'string' },
    { name: 'updatedAtIso', type: 'string' },
  ],
  summary_requests_v3: [
    { name: 'requestKey', type: 'string' }, { name: 'requestType', type: 'string' },
    { name: 'status', type: 'string' }, { name: 'creationLeaseOwner', type: 'string' },
    { name: 'reconciliationStatus', type: 'string' }, { name: 'canonicalRowID', type: 'string' },
    { name: 'creationLeaseUntilIso', type: 'string' }, { name: 'orderedStreamsJson', type: 'string' },
    { name: 'existingDialoguesJson', type: 'string' }, { name: 'expectedLogicalJobKeysJson', type: 'string' },
    { name: 'channel', type: 'string' }, { name: 'threadTS', type: 'string' },
    { name: 'coverageStatus', type: 'string' }, { name: 'availableRolesJson', type: 'string' },
    { name: 'missingRolesJson', type: 'string' }, { name: 'failedLogicalJobKeysJson', type: 'string' },
    { name: 'leaseOwner', type: 'string' }, { name: 'leaseUntilIso', type: 'string' },
    { name: 'summaryAttempt', type: 'number' }, { name: 'nextRetryAtIso', type: 'string' },
    { name: 'errorCode', type: 'string' }, { name: 'inferenceResultJson', type: 'string' },
    { name: 'summaryMarkdown', type: 'string' },
    { name: 'summaryMessageTS', type: 'string' }, { name: 'summaryUploadID', type: 'string' },
    { name: 'manualReviewReason', type: 'string' }, { name: 'manualReviewAtIso', type: 'string' },
    { name: 'manualReviewResolution', type: 'string' },
    { name: 'manualReviewOriginalStage', type: 'string' },
    { name: 'manualResolutionWinnerRowID', type: 'string' },
    { name: 'manualResolutionDecisionID', type: 'string' },
    { name: 'createdAtIso', type: 'string' }, { name: 'updatedAtIso', type: 'string' },
  ],
  automation_errors_v3: [
    { name: 'errorKey', type: 'string' }, { name: 'component', type: 'string' },
    { name: 'reconciliationStatus', type: 'string' }, { name: 'canonicalRowID', type: 'string' },
    { name: 'requestKey', type: 'string' }, { name: 'logicalJobKey', type: 'string' },
    { name: 'attemptKey', type: 'string' }, { name: 'executionID', type: 'string' },
    { name: 'workflowName', type: 'string' }, { name: 'nodeName', type: 'string' },
    { name: 'errorCode', type: 'string' }, { name: 'messageMasked', type: 'string' },
    { name: 'retryable', type: 'boolean' }, { name: 'createdAtIso', type: 'string' },
  ],
};

return Object.entries(schema).map(([tableName, columns]) => ({
  json: { tableName, columnsJson: JSON.stringify(columns), columnCount: columns.length },
}));
